// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStudent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20) {
  return window['go']['main']['App']['AddStudent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20);
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function EditStudent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EditStudent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAdmins() {
  return window['go']['main']['App']['GetAdmins']();
}

export function GetStudents() {
  return window['go']['main']['App']['GetStudents']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}
