// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddStudent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:string,arg17:string,arg18:string,arg19:string,arg20:string):Promise<boolean>;

export function DeleteStudent(arg1:number):Promise<boolean>;

export function EditStudent(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<boolean>;

export function GetAdmins():Promise<Array<main.Admin>>;

export function GetStudents():Promise<Array<main.Student>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Register(arg1:string,arg2:string):Promise<boolean>;
